/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAnchor: typeof import('ant-design-vue/es')['Anchor']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACarousel: typeof import('ant-design-vue/es')['Carousel']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    Banner: typeof import('./src/components/banner.vue')['default']
    Calendar: typeof import('./src/components/Calendar.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ListRider: typeof import('./src/components/ListRider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheBanner: typeof import('./src/components/races/TheBanner.vue')['default']
    TheBannerPro: typeof import('./src/components/TheBannerPro.vue')['default']
    TheCreateRider: typeof import('./src/components/form/TheCreateRider.vue')['default']
    TheCreateTeam: typeof import('./src/components/form/TheCreateTeam.vue')['default']
    TheFooter: typeof import('./src/components/layouts/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/layouts/TheHeader.vue')['default']
    TheHeaderAdmin: typeof import('./src/components/dashboard/TheHeaderAdmin.vue')['default']
    TheHeaderBar: typeof import('./src/components/layouts/TheHeaderBar.vue')['default']
    TheheaderMain: typeof import('./src/components/layouts/TheheaderMain.vue')['default']
    TheInfoRaceNow: typeof import('./src/components/layouts/TheInfoRaceNow.vue')['default']
    TheMenuHome: typeof import('./src/components/TheMenuHome.vue')['default']
    TheProduct: typeof import('./src/components/products/TheProduct.vue')['default']
    TheProductList: typeof import('./src/components/products/TheProductList.vue')['default']
    TheRider: typeof import('./src/components/TheRider.vue')['default']
    TheSideBar: typeof import('./src/components/dashboard/TheSideBar.vue')['default']
  }
}
